# sudo: required
# language: node_js
# node_js:
# - "11.10.1"
# after_success:
# - chmod +x ./deploy.sh
# - "./deploy.sh"

language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  
  app: "micro-node-app-demo"
  env: "production-node"
  on:
    branch: master